### ISSUE TITLE
add example docs about " how to setup  apk cloner script and excute it "

### ISSUE THREAD

**Issue by vishalk17** [RamDurgaSai/ApkCloner#1]
If you could add example docs about " how to setup  apk cloner script and excute it " then it will help other peoples to understand even more better.....

I have setup apk tool path and uber signer app inside config.json

still  I m getting an errors..

**Comment by RamDurgaSai** [comment]
Sorry 
I forgot to uncomment a line (Which Decompile apk)

fixed fix #7

**Comment by RamDurgaSai** [comment]
Sorry 
Forgot to uncomment a line ....

fix #7

**Comment by RamDurgaSai** [comment]
Still facing any errors 
ReOpen issue with Error messages, apk file link(if want share)
